### ISSUE TITLE
How do you instantiate Equation 7?

### ISSUE THREAD

**Issue by enjeeneer** [seohongpark/HILP#1]
Hi Seohong!

Thanks for open-sourcing your code and for the cool paper! I have two quick questions re: pretraining HILPs for zero-shot RL:

1. Is equation 7 (pg. 5) from your paper instantiated by setting `feature_type` to `'diff'`, such that `target_phi` is computed as per the below? 
https://github.com/seohongpark/HILP/blob/a2abbe4cfcced28dbb3bbd937d92040f250eba35/hilp_zsrl/url_benchmark/agent/sf.py#L623-L624
I ask because I note that `feature_type` defaults to `'state'`, not `'diff'`, here:
https://github.com/seohongpark/HILP/blob/a2abbe4cfcced28dbb3bbd937d92040f250eba35/hilp_zsrl/url_benchmark/agent/sf.py#L67
2. Relatedly, in the zero-shot RL section of Appendix D.2, you say you use the centred reward function variant of equation 7. I can't find where you implement that in the codebase, could you direct me to it?

Thanks very much in advance for your help!

Scott

**Comment by seohongpark** [comment]
Hi Scott, thanks for the questions!

1. In zero-shot RL experiments on ExORL, we mainly use the "centered" variant (`(φ(s') - \bar{φ})T z`) mentioned in the "Implementation" paragraph in Section 4.2, which corresponds to `feature_type=state`.
2. You can find it here:
https://github.com/seohongpark/HILP/blob/master/hilp_zsrl/url_benchmark/agent/sf.py#L122

**Comment by enjeeneer** [comment]
Ah, gotcha, understood. Thanks for the quick reply!
