### ISSUE TITLE
Question about visualization of tSNE

### ISSUE THREAD

**Issue by skylooop** [seohongpark/HILP#3]
Hi! Thank you for such a good paper.
However, I have small question: I tried to reproduce your tSNE plot of Hilbert representation for Z=R^32 (on antmaze-large-diverse-v2 with your default settings). Unfortunately, the projection onto 2D does not look as good as yours (there is no visible geometry, similiar to antmaze-large-diverse env ). Can you please share more details on how this was done? I am sampling many states from the D4RL dataset and then passing them through `get_phi` method.
Thanks!

**Comment by seohongpark** [comment]
Hi skylooop,

Thanks for the question. This is a brief code snippet that we used to generate the qualitative plots in the paper. Basically, the gridpoints in the leftmost figure (Figure 10) correspond to the points that we used to obtain $\phi(s)$'s.

```
obs = []
for x in np.arange(-4.25, 40, 0.5):
    for y in np.arange(-4.25, 28, 0.5):
        if not poly_union.contains(Point(x, y))[0]:
            obs.append(np.concatenate([[x, y], dataset['observations'][0][2:]]))
obs = np.array(obs)
ex_phis = np.array(agent.get_phi(obs))

fig, ax = plt.subplots(1, 1, figsize=(10 * 0.8, 10 * 0.8))
tsne_phis = TSNE(n_components=2).fit_transform(ex_phis)
ax.scatter(-tsne_phis[:, 0], tsne_phis[:, 1], c=light_colors, edgecolor=colors, s=8, alpha=1, linewidth=0.5)
```
