### ISSUE TITLE
Question about the implementation

### ISSUE THREAD

**Issue by LongchaoDa** [seohongpark/HILP#4]
Dear authors, 

Thanks for the interesting project!

I was going through the code and found some questions regarding the prompt part. 
Specifically, in the function `infer_meta_from_obs_and_rewards`, I saw the term1:`z = torch.matmul(reward.T, B) / reward.shape[0]`, this  seems to calculate the Expectation of the [r(·)\hat{phi}]. However, I was wondering where is the calculation of the term2:`E [\hat{phi} \hat{phi}_transpose]^{-1}`? 
<img width="422" alt="image" src="https://github.com/user-attachments/assets/9d2e2505-4de3-4ebb-becb-6fd0a21f6377">

Or is it assumed that, the result for term2 is an identity matrix? Why is it like that?

**Comment by seohongpark** [comment]
Hi LongchaoDa,

It seems you're referring to the code for forward-backward (FB) representations, not for successor features (SFs). Please find the relevant code here: https://github.com/seohongpark/HILP/blob/master/hilp_zsrl/url_benchmark/agent/sf.py#L535, where $z$ is computed with `torch.linalg.lstsq`.

**Comment by LongchaoDa** [comment]
Thank you so much, it helps a lot!
